# [2048 Challenge](http://112.137.129.136:8000/problem_view?problem=1)

In [114]:
import numpy as np
import random
import game
import copy
from logic2048 import *

In [115]:
LIM = 200

def Reflection(board):
  tot = [0, 0, 0, 0]
  for i in range(LIM):
    nxt = copy.deepcopy(board)
    OperatingMove(nxt, i % 4)
    SpawnTile(nxt)
    while not IsGameOver(board):
      OperatingMove(nxt, random.randint(0, 3))
      SpawnTile(nxt)
      print(nxt)
    tot[i % 4] += GetScore(nxt)
  return tot.index(max(tot))

In [116]:
# client = game.Client(account, quiz)
# # Code chi choi 1 game.
# # De choi duoc nhieu game, can phai kiem tra xem
# # bang hien tai co phai ket thuc khong
# while client.playing:
#     data = client.get_state()
#     if isinstance(data, game.Board):
#         # Lay mot move bat ky
#         move = game.MOVES[random.randint(0, 3)]
#         # Make move
#         client.make_move(move)
#     elif isinstance(data, game.Game):
#         # Mot game da ket thuc
#         print("Game ended")
#     elif isinstance(data, game.Result):
#         # Tro choi da ket thuc
#         print("Session ended")
#         break

In [117]:
board = np.array([[0, 0, 0, 0], [0, 2, 0, 2], [0, 0, 0, 0], [0, 0, 0, 0]])
print(Reflection(board))

[[0 0 0 0]
 [4 0 0 0]
 [2 0 0 0]
 [0 2 0 0]]
[[0 0 0 0]
 [0 0 0 4]
 [0 0 0 2]
 [4 0 0 2]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 2 0]
 [4 0 0 8]]
[[4 0 2 8]
 [0 0 0 0]
 [0 0 0 0]
 [0 2 0 0]]
[[0 4 2 8]
 [0 0 0 0]
 [0 0 0 4]
 [0 0 0 2]]
[[4 2 8 0]
 [0 2 0 0]
 [4 0 0 0]
 [2 0 0 0]]
[[0 4 2 8]
 [0 0 0 2]
 [0 0 0 4]
 [2 0 0 2]]
[[2 4 2 8]
 [0 0 0 2]
 [2 0 0 4]
 [0 0 0 2]]
[[4 4 2 8]
 [0 0 0 2]
 [0 2 0 4]
 [0 0 0 2]]
[[4 4 2 8]
 [0 2 0 2]
 [0 0 2 4]
 [0 0 0 2]]
[[8 2 8 0]
 [4 0 0 0]
 [2 4 0 2]
 [2 0 0 0]]
[[0 8 2 8]
 [0 2 0 4]
 [0 2 4 2]
 [0 0 0 2]]
[[8 2 8 0]
 [2 4 0 2]
 [2 4 2 0]
 [2 0 0 0]]
[[0 0 0 0]
 [8 2 8 2]
 [2 8 2 2]
 [4 0 0 0]]
[[8 2 8 4]
 [2 8 2 0]
 [4 0 0 0]
 [2 0 0 0]]
[[8 2 8 4]
 [0 2 8 2]
 [0 2 0 4]
 [0 0 0 2]]
[[ 2  0  0  4]
 [ 0  0  0  2]
 [ 0  2 16  4]
 [ 8  4  0  2]]
[[ 0  0  2  4]
 [ 0  2  0  2]
 [ 0  2 16  4]
 [ 0  8  4  2]]
[[ 0  0  2  4]
 [ 0  0  0  4]
 [ 0  2 16  4]
 [ 2  8  4  2]]
[[ 0  2  0  0]
 [ 0  0  2  4]
 [ 0  2 16  8]
 [ 2  8  4  2]]
[[ 2  4  2  4]
 [ 0  8 16  8]
 [ 0  

Traceback (most recent call last):
  File "/home/sekiro/uet/2048-challenger/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_4965/3167072231.py", line 2, in <cell line: 2>
    print(Reflection(board))
  File "/tmp/ipykernel_4965/993364939.py", line 11, in Reflection
    SpawnTile(nxt)
  File "/home/sekiro/uet/2048-challenger/logic2048.py", line 41, in SpawnTile
    return all(not i for i in chk)
  File "/usr/lib/python3.10/random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sekiro/uet/2048-challenger/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 1993, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/home/sekiro/uet/2048-challenger/.venv/

In [118]:
board = [[2, 4, 8, 4], [4, 8, 2, 32], [16, 2, 64, 2], [4, 16, 4, 2]]
print(CheckAvailableMove(board))

[False, True, False, True]
