# [2048 Challenge](http://112.137.129.136:8000/problem_view?problem=1)

In [1]:
from ai import *
from game_board import *
import game
import numpy as np

account = "ayakain5rolls"
quiz = 1

client = game.Client(account, quiz)
board = GameBoard()
ai = AI()

while client.playing:
    data = client.get_state()
    if isinstance(data, game.Board):
        board.grid = np.array(data.board)
        print(board.grid)
        client.make_move(game.MOVES[ai.get_move(board)])
    elif isinstance(data, game.Game):
        print("Game ended")
    elif isinstance(data, game.Result):
        print("Session ended")
        break

[[0 0 0 0]
 [0 0 2 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 2]
 [0 0 0 0]
 [2 0 0 0]]
[[0 0 0 0]
 [0 2 0 2]
 [0 0 0 0]
 [0 0 0 2]]
[[0 0 0 2]
 [0 0 0 0]
 [0 0 0 0]
 [0 2 0 4]]
[[0 2 0 2]
 [0 0 0 4]
 [2 0 0 0]
 [0 0 0 0]]
[[4 0 0 4]
 [0 0 0 4]
 [0 0 0 2]
 [0 0 0 0]]
[[4 0 0 8]
 [0 0 0 2]
 [2 0 0 0]
 [0 0 0 0]]
[[0 0 4 8]
 [0 0 0 2]
 [0 0 0 2]
 [0 0 0 2]]
[[0 0 0 0]
 [0 0 0 8]
 [0 0 0 2]
 [0 2 4 4]]
[[0 0 0 0]
 [8 0 0 0]
 [2 0 2 0]
 [2 8 0 0]]
[[8 8 2 0]
 [4 0 0 0]
 [0 0 2 0]
 [0 0 0 0]]
[[8 8 4 0]
 [4 0 0 0]
 [0 0 0 2]
 [0 0 0 0]]
[[ 0  2 16  4]
 [ 0  0  0  4]
 [ 0  0  0  2]
 [ 0  0  0  0]]
[[ 2  2 16  8]
 [ 0  0  0  2]
 [ 0  0  0  0]
 [ 0  0  0  0]]
[[ 0  4 16  8]
 [ 0  0  0  2]
 [ 0  0  2  0]
 [ 0  0  0  0]]
[[ 0  4 16  8]
 [ 4  0  0  2]
 [ 0  0  0  2]
 [ 0  0  0  0]]
[[ 4  4 16  8]
 [ 4  0  0  4]
 [ 0  0  0  0]
 [ 0  0  0  0]]
[[ 0  8 16  8]
 [ 0  0  0  8]
 [ 0  0  0  4]
 [ 0  0  0  0]]
[[ 0  8 16 16]
 [ 0  0  0  4]
 [ 0  0  0  0]
 [ 0  2  0  0]]
[[ 0  2  8 32]
 [ 0  0  0  4]
 [ 

KeyboardInterrupt: 

In [13]:
board = GameBoard()
board.grid = np.array([[0, 0, 0, 0], [0, 2, 0, 2], [0, 0, 0, 0], [0, 0, 0, 0]])
ai = AI()

print(board.grid)

[[0 0 0 0]
 [0 2 0 2]
 [0 0 0 0]
 [0 0 0 0]]
